### ISSUE TITLE
Etc: github actions CI / CD 설정

### ISSUE THREAD

**Issue by jikimee64** [bsideproject/palette-auth-server#7]
- develop 브랜치에 PR 시 spring.profiles.defualt:dev로 설정 후 진행, server.port 8081로 실행(추후 컨테이너 싫랭시 외부 주입도 추가할 예정)

```
spring:
  profiles:
    default: dev

server:
  port: 8081
```

- mysql8과 같은 도커 네트워크로 묶었기 때문에 컨테이너 이름(mysql8)만으로 커넥션 가능
```
    url: jdbc:mysql://mysql8:3306/palette
```

- application-local.yml, application-dev 분리
  - spring:jpa:database-platform: org.hibernate.dialect.MySQL8Dialect 추가
